@url = http://localhost:3003

### CREATE USER
POST {{url}}/createuser
content-type: application/json
 
{
"user": {
    "firstName": "UserFirstName3333",
    "lastName": "UserLastName",
    "username": "UserName",
    "email": "email@emailbla.de",
    "password1": "12345678",
    "password2": "12345678"
}
}

### READ USERS 
GET {{url}}/users
content-type: application/json

### UPDATE USER
PATCH {{url}}/update/61a78c18f3b06d1572e5d462
content-type: application/json
 
{
    "userName": "ggg333333g",
    "password1": "12345678",
    "password2": "12345678",
    "email": "username1@mail.com"
}

### DELETE USER
DELETE {{url}}/delete/61a7823678165961ad65c16e
content-type: application/json

### LOGIN USERSuserPOST {{url}}/login
content-type: application/json

{
	"userName": "jj",
	"password": "password"
}

### LOGOUT USERS
GET {{url}}/logout
content-type: application/json

{
	"userName": "jj",
	"password": "password"
}