@url = http://localhost:3003

### CREATE user
POST {{url}}/createuser
content-type: application/json
 
{
"user": {
    "firstName": "UserFirstName2222",
    "lastName": "UserLastName",
    "username": "UserName",
    "email": "email@emailbla.de",
    "password1": "12345678",
    "password2": "12345678"
}
}

### READ users 
GET {{url}}/user
content-type: application/json

### UPDATE user
PATCH {{url}}/update/61a78c18f3b06d1572e5d462
content-type: application/json
 
{
    "userName": "ggg333333g",
    "password1": "12345678",
    "password2": "12345678",
    "email": "username1@mail.com"
}

### DELETE user
DELETE {{url}}/delete/61a7823678165961ad65c16e
content-type: application/json

### LOGIN USERS
POST {{url}}/login
content-type: application/json

{
	"userName": "jj",
	"password": "password"
}